### ISSUE TITLE
Controls inside contentView can't get touch events

### ISSUE THREAD

**Issue by andrew-nemtsev** [sberrevoets/SDCAlertView#224] opened 2017-07-31 15:03 UTC
I use _contentView_ to display hyperlink inside of _SDCAlertViewController_.

The problem is any UI control added as subview of _contentView_ can't get touch events.
I have tried "UILabel + UITapGestureRecognizer", "UIButton" and "FRHyperLabel" approaches - non of them allows me to detect user tap at hyperlink.
At the same time _UISwitch_ is the only control which changes it's state being added as subview of  _contentView_ - so Example demo looks like OK till you try to change _UISwitch_ to any other UI control.

I suspect that the reason of this behavior is "UIScrollView > UIView" (the last is contentView) hierarchy.

**Comment by sberrevoets** [comment] 2017-07-31 17:08
I suspect this is a duplicate of https://github.com/sberrevoets/SDCAlertView/issues/140.

**Comment by ReDetection** [comment] 2017-08-31 05:25
this is because header view has interaction disabled from XIB

**Comment by ReDetection** [comment] 2017-08-31 07:13
```
alertController.contentView.isUserInteractionEnabled = true
```
fixes this just fine from our code without need for any MR

**Comment by sberrevoets** [comment] 2017-09-05 06:37
That seems like a good solution 👍  Don't think I want to opt-in everybody to that by enabling this in the XIB, but manually enabling it is no big deal.

**Closed by sberrevoets** 2017-09-05 06:37 UTC
