### ISSUE TITLE
actionTappedHandler not called when shouldDismissHandler for that action is false

### ISSUE THREAD

**Issue by Liampronan** [sberrevoets/SDCAlertView#148] opened 2016-04-14 16:32 UTC
Hi all,

If I create a shouldDismissHandler to prevent the dismissal of an action when it's tapped, then that action's handler is not called. Is this intended behavior? I am looking to prevent dismissal while still calling the action. Here is the related code:

```
self.alertView.actionTappedHandler = { [weak self] action in
            guard self?.shouldDismissHandler?(action) != false else { return }
            self?.dismiss(animated: true) {
                action.handler?(action)
            }
        }
```
https://github.com/sberrevoets/SDCAlertView/blob/master/Source/AlertController.swift#L278-L282

I'm happy to submit a PR if this is not intended behavior.

Thanks!

**Comment by sberrevoets** [comment] 2016-04-14 17:30
Yes, this is more or less intended behavior as I would expect that most of the time you wouldn't want an action to be called when the alert isn't actually dismissed.

However, there is a relatively simple fix for this: in `shouldDismissHandler` you get the action as a parameter, so you can call the `handler` yourself. This requires the `handler` to be made public for at least reading, but maybe writing wouldn't be so bad either.

Feel free to submit a PR! If you do, please also amend the documentation for `shouldDismissHandler` to indicate that if it returns `false` the action handler will not be executed.

Thanks!

**Comment by Liampronan** [comment] 2016-04-19 20:59
Great, thanks @sberrevoets! 

PR submitted with your suggestions: https://github.com/sberrevoets/SDCAlertView/pull/149

**Comment by sberrevoets** [comment] 2016-04-19 21:26
Thanks, let's continue the conversation there!

**Closed by sberrevoets** 2016-04-19 21:26 UTC
Labels: enhancement
