### ISSUE TITLE
Interaction doesn't work anymore

### ISSUE THREAD

**Issue by svachmic** [sberrevoets/SDCAlertView#284] opened 2018-11-20 15:05 UTC
I am using the approach as mentioned in other issues, such as: #254 or #224 but none of it seems to work anymore. Using Xcode 10.1 Swift 4.2.

Code:

```
let controller: ABCViewController = StoryboardType.abc.storyboard().instantiateViewController()
let contentSubview = controller.view!
          
let alert = AlertController(title: "Finish", message: nil)
alert.addAction(AlertAction(title: "Cancel", style: .normal))
alert.addAction(AlertAction(title: "OK", style: .preferred))
        
alert.contentView.isUserInteractionEnabled = true
contentSubview.translatesAutoresizingMaskIntoConstraints = false
alert.contentView.addSubview(contentSubview)
        
NSLayoutConstraint.activate([
            contentSubview.leadingAnchor.constraint(equalTo: alert.contentView.leadingAnchor, constant: 0),
            contentSubview.trailingAnchor.constraint(equalTo: alert.contentView.trailingAnchor, constant: 0),
            contentSubview.topAnchor.constraint(equalTo: alert.contentView.topAnchor, constant: 30),
            contentSubview.bottomAnchor.constraint(equalTo: alert.contentView.bottomAnchor, constant: -50)
])
        
alert.present()
```

Any suggestions? Thanks a lot!

**Comment by sberrevoets** [comment] 2018-11-20 18:21
Few things I'd try:

- Set `clipsToBounds` to `true` on the content view. The content view sizes according to the content you give it, but if that content doesn't have a size the  content view might just not have dimensions.
- Give the content view a background color to see how things are laid out
- Add a simple tap gesture to `contentSubview`. If the tap is triggered it's likely somewhere in your setup, I'd need a sample project to further debug at that point.

**Comment by svachmic** [comment] 2018-11-21 10:54
The subviews have the proper dimensions:

<img width="420" alt="screenshot 2018-11-21 at 09 58 04" src="https://user-images.githubusercontent.com/1448888/48836666-a89a8e00-ed83-11e8-8fbf-4d90368fbfab.png">

`clipsToBounds` on either `contentView` of the alert or my `contentSubview` messes up the layout.

I tried adding a `UITapGestureRecognizer` to **my** `contentSubview` and it **didn't** work. When I added it to the alert's `contentView` I did get the callback fired. Seems like there is no interaction allowed to the controls in my controller.

The setup isn't really that complex - simply a label and a button, centered vertically in the container.

**Comment by svachmic** [comment] 2018-11-21 10:56
Just to add to the picture for a sanity check - the label does not overlap the button. To be perfectly clear. I know it's not obvious from the picture.

**Comment by sberrevoets** [comment] 2018-11-21 18:08
> clipsToBounds on either contentView of the alert or my contentSubview messes up the layout.

That makes it sound like the layout isn't properly defined. What `frame` values do you get for both `contentView` and `contentSubview`?

**Comment by svachmic** [comment] 2018-11-22 10:40
Sorry I should have clarified better what I meant by *messes up* - it actually didn't throw it out of bounds, it moved the layout slightly higher up and made it pixel-close to the header of the dialog.

I checked the frames and the numbers were perfectly normal for what you would expect. Height and width was right and the X and Y values were coherent to what I was looking at.

I dug a bit deeper and found this:
- contentView - user interaction enabled ON
-- contentSubview (the view of my embedded controller) - user interaction enabled ON
--- the lock button - user interaction enabled OFF

No matter what I did - traversing the subviews, enabling the user interaction on all possible levels, I couldn't get a response from the button - just nothing at all. I obviously did the sane thing to try the controller outside of the dialog and simply present it and everything worked well (to be perfectly clear). No output in the console about unsatisfiable constraints.

Anyway, I had to move on, so I actually deleted the code and resorted to a different approach, so I don't have the code anymore. Unless you want to follow up on it and explore this topic further to clarify whether or not it actually is a problem somewhere in the setup of the contentView or if there needs to be a specific setup for any embedded controller, I am happy to let this go and close the issue as I am no longer using this approach.

Thanks for your time!

**Comment by sberrevoets** [comment] 2018-11-22 23:48
At this point I'd need a reproducible project to really understand what is going on. If you are interested in uploading one I can take a look. In the meantime I'll close this since you've solved it in a different manner anyway.

Thanks for the details, feel free to reopen if you want me to take a look at a sample project.

**Closed by sberrevoets** 2018-11-22 23:48 UTC
