### ISSUE TITLE
SDCAlertView takes random / unusually long time to show up

### ISSUE THREAD

**Issue by PeterBenko** [sberrevoets/SDCAlertView#120] opened 2015-11-12 19:40 UTC
Hi,

I tried to incorporate SDCAlertView (3.0.3) to project (Obj-C) of mine but it sometimes took a very long time to present itself.  Sometimes it was fast and snappy, other times it would load only on the next touch anywhere on the screen... 

I tried 3.0 and it was the same. On 2.5.4 everything runs seemingly fine.

The code I used:
```objc
SDCAlertController *alertView = [[SDCAlertController alloc] initWithTitle:@"TITLE"
                                                                  message:@"Message"
                                                           preferredStyle:AlertStyleAlert];
SDCAlertAction* cancelAction = [[SDCAlertAction alloc] initWithTitle:@"Cancel"
                                                               style:AlertActionStylePreferred
                                                             handler:^(SDCAlertAction *action){}];
[alertView addAction:cancelAction];
SDCAlertAction* deleteAction = [[SDCAlertAction alloc] initWithTitle:@"Clear"
                                                               style:AlertActionStyleDestructive
                                                             handler:action];
[alertView addAction:deleteAction];
NSLog(@"PRESENTING");
[alertView presentWithAnimated:YES completion:^(){NSLog(@"PRESENTED");}];
```

Produced:
```
2015-11-12 20:25:39.690 xxx[42988:1722731] PRESENTING
2015-11-12 20:25:44.191 xxx[42988:1722731] PRESENTED
```
I guess my question is if it is me doing something wrong or is there actually an issue?

**Comment by sberrevoets** [comment] 2015-11-12 19:44
Wow, that's ridiculously long. Just to confirm: you are doing this on the main thread? If so, I'd love to see a project that reproduces this as this is the first time I'm seeing it.

**Comment by PeterBenko** [comment] 2015-11-12 19:46
Yes I checked that it was on main, will try again and post results.

**Comment by PeterBenko** [comment] 2015-11-12 19:51
Yep. To be clear:  I intentionally waited on an instance when it did't do anything until I clicked somewhere on the screen, no clue how ling it would take otherwise.

```
2015-11-12 20:48:20.679 Flash Cards[43539:1748417] PRESENTING on <NSThread: 0x7fe942503ff0>{number = 1, name = main}
2015-11-12 20:48:26.275 Flash Cards[43539:1748417] PRESENTED
```

**Comment by sberrevoets** [comment] 2015-11-12 21:56
I see what you mean. I can investigate a little bit, but this is gonna be really difficult without a sample project.

**Comment by PeterBenko** [comment] 2015-11-13 00:05
In an attempt to strip down the project to share it (not under contract, just a trust thing) I first copied all files to delete parts bit by bit. Without editing ANYTHING I'm unable to reproduce the long times from the copied project. Longest times I get now is a bit under a second, most faster. 

Incredibly odd, but as far as I'm concerned this can be marked as cannot reproduce and closed. Please let me know if you'd be interested in testing this remotely, I could screencast or something. Thanks for your fast replies!

**Comment by sberrevoets** [comment] 2015-11-13 00:09
That seems really strange. I'll close this for now, but if you can come up with reproduction steps feel free to reopen!

**Comment by PeterBenko** [comment] 2015-11-13 00:54
Ok, managed to reproduce and sent the project on your blog email. It manifested most often after a long press on the table cell that was supposed to trigger it.

**Comment by sberrevoets** [comment] 2015-11-13 00:58
Ah great, thanks! I'll take a look.

**Comment by sberrevoets** [comment] 2015-11-23 05:16
Even after looking at a sample project that should have reproduced the issue, I wasn't able to. I'm leaving this open in case someone else runs into the same problem, but since I have not been able to see this myself I won't be putting too much time in fixing this.

**Comment by sberrevoets** [comment] 2016-02-21 20:51
Gonna close this again as this doesn't seem like a major to anyone else.

**Closed by sberrevoets** 2016-02-21 20:51 UTC
Labels: invalid
