### ISSUE TITLE
cancel button can not set attributeString

### ISSUE THREAD

**Issue by XHJiang** [sberrevoets/SDCAlertView#195] opened 2016-12-20 06:02 UTC
let alert = AlertController(title: "11", message: "22", preferredStyle: .actionSheet)
            
            let titleStr : NSMutableAttributedString = NSMutableAttributedString(string: alertArr[0])
            titleStr.addAttribute(NSForegroundColorAttributeName, value: UIColor(hex: 0x222222FF), range: NSRange(location: 0 , length: alertArr[0].characters.count))
            
            titleStr.addAttribute(NSFontAttributeName, value: UIFont(name: "Al-Jazeera-Arabic-Bold", size: 20) ?? UIFont.systemFont(ofSize: 20), range: NSRange(location: 0 , length: alertArr[0].characters.count))
            
            alert.add(AlertAction.init(attributedTitle: titleStr, style: .destructive, handler: { (_) in
                TTLog(messsage: "11")
            }))
            alert.add(AlertAction.init(attributedTitle: titleStr, style: .normal, handler: { (_) in
                TTLog(messsage: "22")
            }))
            alert.add(AlertAction.init(attributedTitle: titleStr, style: .normal, handler: { (_) in
                TTLog(messsage: "33")
            }))
            alert.add(AlertAction.init(attributedTitle: titleStr, style: .normal, handler: { (_) in
                TTLog(messsage: "44")
            }))
            
            alert.present()

The first action con not get attributeString, wHY

**Comment by sberrevoets** [comment] 2016-12-20 15:49
I've noticed this behavior before, and I think it's an implementation detail on iOS that's incorrectly documented. Setting `attributedText` after setting the text color (which is what is happening) should reset the label to the contents of the attributed text, but that doesn't happen.

In your case the solution would be to not use `.destructive`, but to specify the `.destructive` style in the attributed string manually.

**Comment by XHJiang** [comment] 2016-12-22 11:05
![image](https://cloud.githubusercontent.com/assets/13825718/21423746/a1644210-c879-11e6-8884-0afcb22b04f4.png)

**Comment by XHJiang** [comment] 2016-12-22 11:10
But ,I have another question. After alert.present(),the alert do not appear, it stay a long time .then alert,I do not know why

**Comment by XHJiang** [comment] 2016-12-22 11:39
I have a great discovery,When I click on the button three times fastly, the alert can alert fast,But when a click onece,  it stay a long time

**Comment by sberrevoets** [comment] 2016-12-22 11:48
Ah yes, I see what the issue is with the attributed string problem. I've pushed a fix to this branch: https://github.com/sberrevoets/SDCAlertView/tree/fix-cancel-color. Can you double-check that this fixes the problem?

As for your presentation issues, please open a separate issue so it's easier to track.

**Comment by sberrevoets** [comment] 2017-02-17 07:42
Closing this for inactivity. The branch I linked to above is still up, feel free to reopen if that fixes your problem so we can get that in master.

**Closed by sberrevoets** 2017-02-17 07:42 UTC
Labels: bug
