### ISSUE TITLE
Using cosmos a star rating control as contentView 

### ISSUE THREAD

**Issue by pepollet** [sberrevoets/SDCAlertView#202] opened 2017-01-30 22:09 UTC
Hi, 

I'm trying to use [Cosmos](https://github.com/marketplacer/Cosmos) and SCVAlertView to present an alert allowing the user to rate an item inside my app.
I'm experiencing a weird behavior with the rating control, the touch events are not registered the way they are when used in other view controllers. You usually can slide your finger over the stars controller to set its value but inside the alert I only can tap on them.

Any idea why when placed inside a SDCAlertView this controller won't react to touch events properly ?

**Comment by sberrevoets** [comment] 2017-01-30 23:16
It sounds like this may be a duplicate of https://github.com/sberrevoets/SDCAlertView/issues/140.

**Comment by pepollet** [comment] 2017-01-31 13:39
Yes it seems like it's the same problem.
Any plan on changing the scrollview behavior as you mention it in your comment on #140 ?

**Comment by sberrevoets** [comment] 2017-02-17 07:38
Plan? Sure. Time? Not much lately :) But feel free to submit a PR!

**Comment by sberrevoets** [comment] 2017-02-17 07:39
Going to close this since it's a duplicate.

**Closed by sberrevoets** 2017-02-17 07:39 UTC
Labels: duplicate
