### ISSUE TITLE
Alert fails to show if a prior alert was dismissed ~1 second or less prior.

### ISSUE THREAD

**Issue by haseebq** [sberrevoets/SDCAlertView#125] opened 2015-11-23 17:58 UTC
If alerts are shown in quick succession (i.e. first dismiss an alert and then shown another right after dismissing the prior alert) [SDCAlertController presentWithAnimated] fails with the following message:

Warning: Attempt to present "SDCAlertController: 0x7f9b99ab0760" on "SDCAlertController: 0x7f9b9fd44af0" whose view is not in the window hierarchy!

The workaround seems to be to wait atleast a second or two before calling presentWithAnimated. Any ideas why this is happening?

**Comment by sberrevoets** [comment] 2015-11-23 18:55
Yeah this is more or less expected. You can't present on view controllers that haven't been fully presented yet. If you try the same with `UIAlertController`, it will give you that same warning.

The solution is a system that's a little more flexible, which I'm planning to implement but haven't gotten to yet. See #112.

**Comment by sberrevoets** [comment] 2020-05-02 08:19
Closing this as a duplicate of #112

**Closed by sberrevoets** 2020-05-02 08:19 UTC
Labels: duplicate, enhancement
