### ISSUE TITLE
UISlider/UIButton inside custom view

### ISSUE THREAD

**Issue by asimonv** [sberrevoets/SDCAlertView#193] opened 2016-12-15 18:16 UTC
It seems that buttons, sliders, etc cannot be touched when I add a custom to to contentView :-/
Is there a way to fix this?

**Comment by sberrevoets** [comment] 2016-12-15 19:36
Could this be related to https://github.com/sberrevoets/SDCAlertView/issues/140?

**Comment by asimonv** [comment] 2016-12-15 21:06
It seems to! Which ```UIScrollView``` should I check?

**Comment by sberrevoets** [comment] 2016-12-15 21:16
The one that gets instantiated [here](https://github.com/sberrevoets/SDCAlertView/blob/master/Source/Views/AlertView.swift#L19) is a good starting point I think.

**Comment by sberrevoets** [comment] 2017-02-17 07:41
Going to assume this is a duplicate of the previously mentioned issue so I'm closing this one. If it turns out to be a different problem, feel free to reopen!

**Closed by sberrevoets** 2017-02-17 07:41 UTC
Labels: duplicate
